/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GamesCodeRouteImport } from './routes/games/$code'
import { Route as PartnersCodeRouteImport } from './routes/partners/$code'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiTablesRoomIdEventsRouteImport } from './routes/api/tables/$roomId/events'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesCodeRoute = GamesCodeRouteImport.update({
  id: '/games/$code',
  path: '/games/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersCodeRoute = PartnersCodeRouteImport.update({
  id: '/partners/$code',
  path: '/partners/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTablesRoomIdEventsRoute = ApiTablesRoomIdEventsRouteImport.update({
  id: '/api/tables/$roomId/events',
  path: '/api/tables/$roomId/events',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/games/$code': typeof GamesCodeRoute
  '/partners/$code': typeof PartnersCodeRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/tables/$roomId/events': typeof ApiTablesRoomIdEventsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/games/$code': typeof GamesCodeRoute
  '/partners/$code': typeof PartnersCodeRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/tables/$roomId/events': typeof ApiTablesRoomIdEventsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/games/$code': typeof GamesCodeRoute
  '/partners/$code': typeof PartnersCodeRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/tables/$roomId/events': typeof ApiTablesRoomIdEventsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/games/$code'
    | '/partners/$code'
    | '/api/auth/$'
    | '/api/tables/$roomId/events'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/games/$code'
    | '/partners/$code'
    | '/api/auth/$'
    | '/api/tables/$roomId/events'
  id:
    | '__root__'
    | '/'
    | '/games/$code'
    | '/partners/$code'
    | '/api/auth/$'
    | '/api/tables/$roomId/events'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GamesCodeRoute: typeof GamesCodeRoute
  PartnersCodeRoute: typeof PartnersCodeRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTablesRoomIdEventsRoute: typeof ApiTablesRoomIdEventsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$code': {
      id: '/games/$code'
      path: '/games/$code'
      fullPath: '/games/$code'
      preLoaderRoute: typeof GamesCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners/$code': {
      id: '/partners/$code'
      path: '/partners/$code'
      fullPath: '/partners/$code'
      preLoaderRoute: typeof PartnersCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tables/$roomId/events': {
      id: '/api/tables/$roomId/events'
      path: '/api/tables/$roomId/events'
      fullPath: '/api/tables/$roomId/events'
      preLoaderRoute: typeof ApiTablesRoomIdEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GamesCodeRoute: GamesCodeRoute,
  PartnersCodeRoute: PartnersCodeRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTablesRoomIdEventsRoute: ApiTablesRoomIdEventsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
