/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedGamesCodeRouteImport } from './routes/_authenticated/games/$code'
import { Route as AuthenticatedPartnersCodeRouteImport } from './routes/_authenticated/partners/$code'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiTablesRoomIdEventsRouteImport } from './routes/api/tables/$roomId/events'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGamesCodeRoute = AuthenticatedGamesCodeRouteImport.update({
  id: '/games/$code',
  path: '/games/$code',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPartnersCodeRoute =
  AuthenticatedPartnersCodeRouteImport.update({
    id: '/partners/$code',
    path: '/partners/$code',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTablesRoomIdEventsRoute = ApiTablesRoomIdEventsRouteImport.update({
  id: '/api/tables/$roomId/events',
  path: '/api/tables/$roomId/events',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/sign-in': typeof SignInRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/games/$code': typeof AuthenticatedGamesCodeRoute
  '/partners/$code': typeof AuthenticatedPartnersCodeRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/tables/$roomId/events': typeof ApiTablesRoomIdEventsRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof SignInRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/': typeof AuthenticatedIndexRoute
  '/games/$code': typeof AuthenticatedGamesCodeRoute
  '/partners/$code': typeof AuthenticatedPartnersCodeRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/tables/$roomId/events': typeof ApiTablesRoomIdEventsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/games/$code': typeof AuthenticatedGamesCodeRoute
  '/_authenticated/partners/$code': typeof AuthenticatedPartnersCodeRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/tables/$roomId/events': typeof ApiTablesRoomIdEventsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/history'
    | '/games/$code'
    | '/partners/$code'
    | '/api/auth/$'
    | '/api/tables/$roomId/events'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/history'
    | '/'
    | '/games/$code'
    | '/partners/$code'
    | '/api/auth/$'
    | '/api/tables/$roomId/events'
  id:
    | '__root__'
    | '/_authenticated'
    | '/sign-in'
    | '/_authenticated/history'
    | '/_authenticated/'
    | '/_authenticated/games/$code'
    | '/_authenticated/partners/$code'
    | '/api/auth/$'
    | '/api/tables/$roomId/events'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  SignInRoute: typeof SignInRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTablesRoomIdEventsRoute: typeof ApiTablesRoomIdEventsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/games/$code': {
      id: '/_authenticated/games/$code'
      path: '/games/$code'
      fullPath: '/games/$code'
      preLoaderRoute: typeof AuthenticatedGamesCodeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/partners/$code': {
      id: '/_authenticated/partners/$code'
      path: '/partners/$code'
      fullPath: '/partners/$code'
      preLoaderRoute: typeof AuthenticatedPartnersCodeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tables/$roomId/events': {
      id: '/api/tables/$roomId/events'
      path: '/api/tables/$roomId/events'
      fullPath: '/api/tables/$roomId/events'
      preLoaderRoute: typeof ApiTablesRoomIdEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedGamesCodeRoute: typeof AuthenticatedGamesCodeRoute
  AuthenticatedPartnersCodeRoute: typeof AuthenticatedPartnersCodeRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedGamesCodeRoute: AuthenticatedGamesCodeRoute,
  AuthenticatedPartnersCodeRoute: AuthenticatedPartnersCodeRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  SignInRoute: SignInRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTablesRoomIdEventsRoute: ApiTablesRoomIdEventsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
